/*
 * SPDX-FileCopyrightText: 2016 The Android Open Source Project
 *
 * SPDX-License-Identifier: Apache-2.0
 */

//
// A2DP constants for aptX-HD codec
//

#ifndef A2DP_VENDOR_APTX_HD_CONSTANTS_H
#define A2DP_VENDOR_APTX_HD_CONSTANTS_H

/* aptX-HD codec specific settings */
#define A2DP_APTX_HD_CODEC_LEN 13

#define A2DP_APTX_HD_VENDOR_ID 0x000000D7
#define A2DP_APTX_HD_CODEC_ID_BLUETOOTH 0x0024
#define A2DP_APTX_HD_SAMPLERATE_44100 0x20
#define A2DP_APTX_HD_SAMPLERATE_48000 0x10
#define A2DP_APTX_HD_CHANNELS_STEREO 0x02
#define A2DP_APTX_HD_CHANNELS_MONO 0x01
#define A2DP_APTX_HD_ACL_SPRINT_RESERVED0 0x00
#define A2DP_APTX_HD_ACL_SPRINT_RESERVED1 0x00
#define A2DP_APTX_HD_ACL_SPRINT_RESERVED2 0x00
#define A2DP_APTX_HD_ACL_SPRINT_RESERVED3 0x00

#endif  // A2DP_VENDOR_APTX_HD_CONSTANTS_H
